//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPLookupTableService.CustomTables {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:kpmg:eu:generic:basis:services", ConfigurationName="CustomTables.CustomTableRead_Outb")]
    public interface CustomTableRead_Outb {
        
        // CODEGEN: Generating message contract since the operation CustomTableReadQuery is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAPLookupTableService.CustomTables.CustomTableReadQueryResponse CustomTableReadQuery(SAPLookupTableService.CustomTables.CustomTableReadQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SAPLookupTableService.CustomTables.CustomTableReadQueryResponse> CustomTableReadQueryAsync(SAPLookupTableService.CustomTables.CustomTableReadQueryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kpmg:eu:generic:basis:services")]
    public partial class CustomTableQuery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tableNameField;
        
        private string languageField;
        
        private CustomTableQueryRows[] rowsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("TableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rows", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public CustomTableQueryRows[] Rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
                this.RaisePropertyChanged("Rows");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:kpmg:eu:generic:basis:services")]
    public partial class CustomTableQueryRows : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kpmg:eu:generic:basis:services")]
    public partial class CustomTableResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tableNameField;
        
        private CustomTableResponseRows[] rowsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("TableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rows", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CustomTableResponseRows[] Rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
                this.RaisePropertyChanged("Rows");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:kpmg:eu:generic:basis:services")]
    public partial class CustomTableResponseRows : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string languageField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomTableReadQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:kpmg:eu:generic:basis:services", Order=0)]
        public SAPLookupTableService.CustomTables.CustomTableQuery CustomTableReadQuery;
        
        public CustomTableReadQueryRequest() {
        }
        
        public CustomTableReadQueryRequest(SAPLookupTableService.CustomTables.CustomTableQuery CustomTableReadQuery) {
            this.CustomTableReadQuery = CustomTableReadQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomTableReadQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:kpmg:eu:generic:basis:services", Order=0)]
        public SAPLookupTableService.CustomTables.CustomTableResponse CustomTableReadResponse;
        
        public CustomTableReadQueryResponse() {
        }
        
        public CustomTableReadQueryResponse(SAPLookupTableService.CustomTables.CustomTableResponse CustomTableReadResponse) {
            this.CustomTableReadResponse = CustomTableReadResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomTableRead_OutbChannel : SAPLookupTableService.CustomTables.CustomTableRead_Outb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomTableRead_OutbClient : System.ServiceModel.ClientBase<SAPLookupTableService.CustomTables.CustomTableRead_Outb>, SAPLookupTableService.CustomTables.CustomTableRead_Outb {
        
        public CustomTableRead_OutbClient() {
        }
        
        public CustomTableRead_OutbClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomTableRead_OutbClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomTableRead_OutbClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomTableRead_OutbClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAPLookupTableService.CustomTables.CustomTableReadQueryResponse SAPLookupTableService.CustomTables.CustomTableRead_Outb.CustomTableReadQuery(SAPLookupTableService.CustomTables.CustomTableReadQueryRequest request) {
            return base.Channel.CustomTableReadQuery(request);
        }
        
        public SAPLookupTableService.CustomTables.CustomTableResponse CustomTableReadQuery(SAPLookupTableService.CustomTables.CustomTableQuery CustomTableReadQuery1) {
            SAPLookupTableService.CustomTables.CustomTableReadQueryRequest inValue = new SAPLookupTableService.CustomTables.CustomTableReadQueryRequest();
            inValue.CustomTableReadQuery = CustomTableReadQuery1;
            SAPLookupTableService.CustomTables.CustomTableReadQueryResponse retVal = ((SAPLookupTableService.CustomTables.CustomTableRead_Outb)(this)).CustomTableReadQuery(inValue);
            return retVal.CustomTableReadResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAPLookupTableService.CustomTables.CustomTableReadQueryResponse> SAPLookupTableService.CustomTables.CustomTableRead_Outb.CustomTableReadQueryAsync(SAPLookupTableService.CustomTables.CustomTableReadQueryRequest request) {
            return base.Channel.CustomTableReadQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAPLookupTableService.CustomTables.CustomTableReadQueryResponse> CustomTableReadQueryAsync(SAPLookupTableService.CustomTables.CustomTableQuery CustomTableReadQuery) {
            SAPLookupTableService.CustomTables.CustomTableReadQueryRequest inValue = new SAPLookupTableService.CustomTables.CustomTableReadQueryRequest();
            inValue.CustomTableReadQuery = CustomTableReadQuery;
            return ((SAPLookupTableService.CustomTables.CustomTableRead_Outb)(this)).CustomTableReadQueryAsync(inValue);
        }
    }
}
