//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPLookupTableService.NonChargeableCode {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class StandardMessageFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeFaultData standardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
                this.RaisePropertyChanged("standard");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kpmg:de:erp:nonsap:fin:nonchargeablecode")]
    public partial class ExchangeFaultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText {
            get {
                return this.faultTextField;
            }
            set {
                this.faultTextField = value;
                this.RaisePropertyChanged("faultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl {
            get {
                return this.faultUrlField;
            }
            set {
                this.faultUrlField = value;
                this.RaisePropertyChanged("faultUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                this.faultDetailField = value;
                this.RaisePropertyChanged("faultDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kpmg:de:erp:nonsap:fin:nonchargeablecode")]
    public partial class ExchangeLogData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kpmg:de:erp:sap:fin:internalorderaccounting")]
    public partial class UserStatusForOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusProfileField;
        
        private string userStatusField;
        
        private string statusOrderNumberField;
        
        private string individualObjectStatusIDField;
        
        private string objectStatusDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string StatusProfile {
            get {
                return this.statusProfileField;
            }
            set {
                this.statusProfileField = value;
                this.RaisePropertyChanged("StatusProfile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string UserStatus {
            get {
                return this.userStatusField;
            }
            set {
                this.userStatusField = value;
                this.RaisePropertyChanged("UserStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string StatusOrderNumber {
            get {
                return this.statusOrderNumberField;
            }
            set {
                this.statusOrderNumberField = value;
                this.RaisePropertyChanged("StatusOrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IndividualObjectStatusID {
            get {
                return this.individualObjectStatusIDField;
            }
            set {
                this.individualObjectStatusIDField = value;
                this.RaisePropertyChanged("IndividualObjectStatusID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ObjectStatusDescription {
            get {
                return this.objectStatusDescriptionField;
            }
            set {
                this.objectStatusDescriptionField = value;
                this.RaisePropertyChanged("ObjectStatusDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kpmg:de:erp:sap:fin:internalorderaccounting")]
    public partial class SystemStatusForOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string systemStatusField;
        
        private string individualObjectStatusField;
        
        private string objectStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SystemStatus {
            get {
                return this.systemStatusField;
            }
            set {
                this.systemStatusField = value;
                this.RaisePropertyChanged("SystemStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IndividualObjectStatus {
            get {
                return this.individualObjectStatusField;
            }
            set {
                this.individualObjectStatusField = value;
                this.RaisePropertyChanged("IndividualObjectStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ObjectStatus {
            get {
                return this.objectStatusField;
            }
            set {
                this.objectStatusField = value;
                this.RaisePropertyChanged("ObjectStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kpmg:de:erp:sap:fin:internalorderaccounting")]
    public partial class InternalOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderNumberField;
        
        private string orderTypeField;
        
        private string descriptionField;
        
        private string externalOrderNumberField;
        
        private string objectNumberField;
        
        private string controllingAreaField;
        
        private string companyCodeField;
        
        private string businessAreaField;
        
        private string plantField;
        
        private string profitCenterField;
        
        private string responsibleCostCenterField;
        
        private string wBS_Element_IDField;
        
        private string wBS_Element_TextField;
        
        private string requestingCostCenterField;
        
        private string requestingCompanyCodeField;
        
        private string chargeableCodeField;
        
        private string itemNumberSalesOrderField;
        
        private string taxJurisdictionField;
        
        private string costCenterPostedToField;
        
        private string orderCurrencyField;
        
        private string costingSheetField;
        
        private string overheadKeyField;
        
        private string resultsAnalysisKeyField;
        
        private string interestProfileCalculationField;
        
        private string branchOfficeField;
        
        private string classificationField;
        
        private string engagementPartnerField;
        
        private string engagementManagerField;
        
        private string estimatedOrderTotalCostsField;
        
        private System.DateTime applicationDateField;
        
        private bool applicationDateFieldSpecified;
        
        private string departmentField;
        
        private System.DateTime workStartField;
        
        private bool workStartFieldSpecified;
        
        private System.DateTime endOfWorkField;
        
        private bool endOfWorkFieldSpecified;
        
        private string identifierEquivalenceOrderField;
        
        private string processingGroupField;
        
        private System.DateTime plannedReleaseDateField;
        
        private bool plannedReleaseDateFieldSpecified;
        
        private System.DateTime plannedCompletionDateField;
        
        private bool plannedCompletionDateFieldSpecified;
        
        private System.DateTime plannedClosingDateField;
        
        private bool plannedClosingDateFieldSpecified;
        
        private string requestingOrderField;
        
        private string functionalAreaShortTextField;
        
        private string functionalAreaLongTextField;
        
        private string userResponsibleOfInternalOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("OrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
                this.RaisePropertyChanged("OrderType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ExternalOrderNumber {
            get {
                return this.externalOrderNumberField;
            }
            set {
                this.externalOrderNumberField = value;
                this.RaisePropertyChanged("ExternalOrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ObjectNumber {
            get {
                return this.objectNumberField;
            }
            set {
                this.objectNumberField = value;
                this.RaisePropertyChanged("ObjectNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ControllingArea {
            get {
                return this.controllingAreaField;
            }
            set {
                this.controllingAreaField = value;
                this.RaisePropertyChanged("ControllingArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
                this.RaisePropertyChanged("CompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string BusinessArea {
            get {
                return this.businessAreaField;
            }
            set {
                this.businessAreaField = value;
                this.RaisePropertyChanged("BusinessArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
                this.RaisePropertyChanged("Plant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ProfitCenter {
            get {
                return this.profitCenterField;
            }
            set {
                this.profitCenterField = value;
                this.RaisePropertyChanged("ProfitCenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ResponsibleCostCenter {
            get {
                return this.responsibleCostCenterField;
            }
            set {
                this.responsibleCostCenterField = value;
                this.RaisePropertyChanged("ResponsibleCostCenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=11)]
        public string WBS_Element_ID {
            get {
                return this.wBS_Element_IDField;
            }
            set {
                this.wBS_Element_IDField = value;
                this.RaisePropertyChanged("WBS_Element_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string WBS_Element_Text {
            get {
                return this.wBS_Element_TextField;
            }
            set {
                this.wBS_Element_TextField = value;
                this.RaisePropertyChanged("WBS_Element_Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string RequestingCostCenter {
            get {
                return this.requestingCostCenterField;
            }
            set {
                this.requestingCostCenterField = value;
                this.RaisePropertyChanged("RequestingCostCenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string RequestingCompanyCode {
            get {
                return this.requestingCompanyCodeField;
            }
            set {
                this.requestingCompanyCodeField = value;
                this.RaisePropertyChanged("RequestingCompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string ChargeableCode {
            get {
                return this.chargeableCodeField;
            }
            set {
                this.chargeableCodeField = value;
                this.RaisePropertyChanged("ChargeableCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=16)]
        public string ItemNumberSalesOrder {
            get {
                return this.itemNumberSalesOrderField;
            }
            set {
                this.itemNumberSalesOrderField = value;
                this.RaisePropertyChanged("ItemNumberSalesOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string TaxJurisdiction {
            get {
                return this.taxJurisdictionField;
            }
            set {
                this.taxJurisdictionField = value;
                this.RaisePropertyChanged("TaxJurisdiction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string CostCenterPostedTo {
            get {
                return this.costCenterPostedToField;
            }
            set {
                this.costCenterPostedToField = value;
                this.RaisePropertyChanged("CostCenterPostedTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=19)]
        public string OrderCurrency {
            get {
                return this.orderCurrencyField;
            }
            set {
                this.orderCurrencyField = value;
                this.RaisePropertyChanged("OrderCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string CostingSheet {
            get {
                return this.costingSheetField;
            }
            set {
                this.costingSheetField = value;
                this.RaisePropertyChanged("CostingSheet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string OverheadKey {
            get {
                return this.overheadKeyField;
            }
            set {
                this.overheadKeyField = value;
                this.RaisePropertyChanged("OverheadKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string ResultsAnalysisKey {
            get {
                return this.resultsAnalysisKeyField;
            }
            set {
                this.resultsAnalysisKeyField = value;
                this.RaisePropertyChanged("ResultsAnalysisKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string InterestProfileCalculation {
            get {
                return this.interestProfileCalculationField;
            }
            set {
                this.interestProfileCalculationField = value;
                this.RaisePropertyChanged("InterestProfileCalculation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string BranchOffice {
            get {
                return this.branchOfficeField;
            }
            set {
                this.branchOfficeField = value;
                this.RaisePropertyChanged("BranchOffice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string Classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
                this.RaisePropertyChanged("Classification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string EngagementPartner {
            get {
                return this.engagementPartnerField;
            }
            set {
                this.engagementPartnerField = value;
                this.RaisePropertyChanged("EngagementPartner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string EngagementManager {
            get {
                return this.engagementManagerField;
            }
            set {
                this.engagementManagerField = value;
                this.RaisePropertyChanged("EngagementManager");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string EstimatedOrderTotalCosts {
            get {
                return this.estimatedOrderTotalCostsField;
            }
            set {
                this.estimatedOrderTotalCostsField = value;
                this.RaisePropertyChanged("EstimatedOrderTotalCosts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=29)]
        public System.DateTime ApplicationDate {
            get {
                return this.applicationDateField;
            }
            set {
                this.applicationDateField = value;
                this.RaisePropertyChanged("ApplicationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApplicationDateSpecified {
            get {
                return this.applicationDateFieldSpecified;
            }
            set {
                this.applicationDateFieldSpecified = value;
                this.RaisePropertyChanged("ApplicationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("Department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=31)]
        public System.DateTime WorkStart {
            get {
                return this.workStartField;
            }
            set {
                this.workStartField = value;
                this.RaisePropertyChanged("WorkStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WorkStartSpecified {
            get {
                return this.workStartFieldSpecified;
            }
            set {
                this.workStartFieldSpecified = value;
                this.RaisePropertyChanged("WorkStartSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=32)]
        public System.DateTime EndOfWork {
            get {
                return this.endOfWorkField;
            }
            set {
                this.endOfWorkField = value;
                this.RaisePropertyChanged("EndOfWork");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndOfWorkSpecified {
            get {
                return this.endOfWorkFieldSpecified;
            }
            set {
                this.endOfWorkFieldSpecified = value;
                this.RaisePropertyChanged("EndOfWorkSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string IdentifierEquivalenceOrder {
            get {
                return this.identifierEquivalenceOrderField;
            }
            set {
                this.identifierEquivalenceOrderField = value;
                this.RaisePropertyChanged("IdentifierEquivalenceOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=34)]
        public string ProcessingGroup {
            get {
                return this.processingGroupField;
            }
            set {
                this.processingGroupField = value;
                this.RaisePropertyChanged("ProcessingGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=35)]
        public System.DateTime PlannedReleaseDate {
            get {
                return this.plannedReleaseDateField;
            }
            set {
                this.plannedReleaseDateField = value;
                this.RaisePropertyChanged("PlannedReleaseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlannedReleaseDateSpecified {
            get {
                return this.plannedReleaseDateFieldSpecified;
            }
            set {
                this.plannedReleaseDateFieldSpecified = value;
                this.RaisePropertyChanged("PlannedReleaseDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=36)]
        public System.DateTime PlannedCompletionDate {
            get {
                return this.plannedCompletionDateField;
            }
            set {
                this.plannedCompletionDateField = value;
                this.RaisePropertyChanged("PlannedCompletionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlannedCompletionDateSpecified {
            get {
                return this.plannedCompletionDateFieldSpecified;
            }
            set {
                this.plannedCompletionDateFieldSpecified = value;
                this.RaisePropertyChanged("PlannedCompletionDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=37)]
        public System.DateTime PlannedClosingDate {
            get {
                return this.plannedClosingDateField;
            }
            set {
                this.plannedClosingDateField = value;
                this.RaisePropertyChanged("PlannedClosingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlannedClosingDateSpecified {
            get {
                return this.plannedClosingDateFieldSpecified;
            }
            set {
                this.plannedClosingDateFieldSpecified = value;
                this.RaisePropertyChanged("PlannedClosingDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string RequestingOrder {
            get {
                return this.requestingOrderField;
            }
            set {
                this.requestingOrderField = value;
                this.RaisePropertyChanged("RequestingOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string FunctionalAreaShortText {
            get {
                return this.functionalAreaShortTextField;
            }
            set {
                this.functionalAreaShortTextField = value;
                this.RaisePropertyChanged("FunctionalAreaShortText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string FunctionalAreaLongText {
            get {
                return this.functionalAreaLongTextField;
            }
            set {
                this.functionalAreaLongTextField = value;
                this.RaisePropertyChanged("FunctionalAreaLongText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string UserResponsibleOfInternalOrder {
            get {
                return this.userResponsibleOfInternalOrderField;
            }
            set {
                this.userResponsibleOfInternalOrderField = value;
                this.RaisePropertyChanged("UserResponsibleOfInternalOrder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kpmg:de:erp:sap:fin:internalorderaccounting")]
    public partial class ProcessingReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string processingReturnCodeField;
        
        private string processingMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string ProcessingReturnCode {
            get {
                return this.processingReturnCodeField;
            }
            set {
                this.processingReturnCodeField = value;
                this.RaisePropertyChanged("ProcessingReturnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ProcessingMessage {
            get {
                return this.processingMessageField;
            }
            set {
                this.processingMessageField = value;
                this.RaisePropertyChanged("ProcessingMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kpmg:de:erp:sap:fin:internalorderaccounting")]
    public partial class InternalOrderResponseDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InternalOrderResponseDetailsMessageHeader messageHeaderField;
        
        private InternalOrder internalOrderField;
        
        private SystemStatusForOrder[] systemStatusForOrderField;
        
        private UserStatusForOrder[] userStatusForOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public InternalOrderResponseDetailsMessageHeader MessageHeader {
            get {
                return this.messageHeaderField;
            }
            set {
                this.messageHeaderField = value;
                this.RaisePropertyChanged("MessageHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public InternalOrder InternalOrder {
            get {
                return this.internalOrderField;
            }
            set {
                this.internalOrderField = value;
                this.RaisePropertyChanged("InternalOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SystemStatusForOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public SystemStatusForOrder[] SystemStatusForOrder {
            get {
                return this.systemStatusForOrderField;
            }
            set {
                this.systemStatusForOrderField = value;
                this.RaisePropertyChanged("SystemStatusForOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UserStatusForOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public UserStatusForOrder[] UserStatusForOrder {
            get {
                return this.userStatusForOrderField;
            }
            set {
                this.userStatusForOrderField = value;
                this.RaisePropertyChanged("UserStatusForOrder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:kpmg:de:erp:sap:fin:internalorderaccounting")]
    public partial class InternalOrderResponseDetailsMessageHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProcessingReturn processingReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ProcessingReturn ProcessingReturn {
            get {
                return this.processingReturnField;
            }
            set {
                this.processingReturnField = value;
                this.RaisePropertyChanged("ProcessingReturn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kpmg:de:erp:sap:fin:internalorderaccounting")]
    public partial class InternalOrderQueryByID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("OrderNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:kpmg:de:erp:nonsap:fin:nonchargeablecode", ConfigurationName="NonChargeableCode.NonChargeableCodeByIDQuery_Outb")]
    public interface NonChargeableCodeByIDQuery_Outb {
        
        // CODEGEN: Generating message contract since the operation NonChargeableCodeByIDReadQuery is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SAPLookupTableService.NonChargeableCode.StandardMessageFault), Action="http://sap.com/xi/WebService/soap1.1", Name="StandardMessageFault", Namespace="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDReadQueryResponse NonChargeableCodeByIDReadQuery(SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDReadQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDReadQueryResponse> NonChargeableCodeByIDReadQueryAsync(SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDReadQueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NonChargeableCodeByIDReadQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:kpmg:de:erp:nonsap:fin:nonchargeablecode", Order=0)]
        public SAPLookupTableService.NonChargeableCode.InternalOrderQueryByID NonChargeableCodeReadQuery;
        
        public NonChargeableCodeByIDReadQueryRequest() {
        }
        
        public NonChargeableCodeByIDReadQueryRequest(SAPLookupTableService.NonChargeableCode.InternalOrderQueryByID NonChargeableCodeReadQuery) {
            this.NonChargeableCodeReadQuery = NonChargeableCodeReadQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NonChargeableCodeByIDReadQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:kpmg:de:erp:nonsap:fin:nonchargeablecode", Order=0)]
        public SAPLookupTableService.NonChargeableCode.InternalOrderResponseDetails NonChargeableCodeReadResponse;
        
        public NonChargeableCodeByIDReadQueryResponse() {
        }
        
        public NonChargeableCodeByIDReadQueryResponse(SAPLookupTableService.NonChargeableCode.InternalOrderResponseDetails NonChargeableCodeReadResponse) {
            this.NonChargeableCodeReadResponse = NonChargeableCodeReadResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NonChargeableCodeByIDQuery_OutbChannel : SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDQuery_Outb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NonChargeableCodeByIDQuery_OutbClient : System.ServiceModel.ClientBase<SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDQuery_Outb>, SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDQuery_Outb {
        
        public NonChargeableCodeByIDQuery_OutbClient() {
        }
        
        public NonChargeableCodeByIDQuery_OutbClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NonChargeableCodeByIDQuery_OutbClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NonChargeableCodeByIDQuery_OutbClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NonChargeableCodeByIDQuery_OutbClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDReadQueryResponse SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDQuery_Outb.NonChargeableCodeByIDReadQuery(SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDReadQueryRequest request) {
            return base.Channel.NonChargeableCodeByIDReadQuery(request);
        }
        
        public SAPLookupTableService.NonChargeableCode.InternalOrderResponseDetails NonChargeableCodeByIDReadQuery(SAPLookupTableService.NonChargeableCode.InternalOrderQueryByID NonChargeableCodeReadQuery) {
            SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDReadQueryRequest inValue = new SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDReadQueryRequest();
            inValue.NonChargeableCodeReadQuery = NonChargeableCodeReadQuery;
            SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDReadQueryResponse retVal = ((SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDQuery_Outb)(this)).NonChargeableCodeByIDReadQuery(inValue);
            return retVal.NonChargeableCodeReadResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDReadQueryResponse> SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDQuery_Outb.NonChargeableCodeByIDReadQueryAsync(SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDReadQueryRequest request) {
            return base.Channel.NonChargeableCodeByIDReadQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDReadQueryResponse> NonChargeableCodeByIDReadQueryAsync(SAPLookupTableService.NonChargeableCode.InternalOrderQueryByID NonChargeableCodeReadQuery) {
            SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDReadQueryRequest inValue = new SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDReadQueryRequest();
            inValue.NonChargeableCodeReadQuery = NonChargeableCodeReadQuery;
            return ((SAPLookupTableService.NonChargeableCode.NonChargeableCodeByIDQuery_Outb)(this)).NonChargeableCodeByIDReadQueryAsync(inValue);
        }
    }
}
