//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("", ClrNamespace="GeneratedNamespace1")]

namespace KMPGSapNonChargeableCodeCrmOutbound
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "urn:kpmg:de:erp:nonsap:fin:nonchargeablecode", ConfigurationName = "NonChargeableCodeByIDQuery_Outb")]
    public interface NonChargeableCodeByIDQuery_Outb
    {

        // CODEGEN: Generating message contract since the operation NonChargeableCodeByIDReadQuery is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "http://sap.com/xi/WebService/soap1.1", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GeneratedNamespace1.StandardMessageFault), Action = "http://sap.com/xi/WebService/soap1.1", Name = "StandardMessageFault", Namespace = "")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        NonChargeableCodeByIDReadQueryResponse NonChargeableCodeByIDReadQuery(NonChargeableCodeByIDReadQueryRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://sap.com/xi/WebService/soap1.1", ReplyAction = "*")]
        System.Threading.Tasks.Task<NonChargeableCodeByIDReadQueryResponse> NonChargeableCodeByIDReadQueryAsync(NonChargeableCodeByIDReadQueryRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:kpmg:de:erp:sap:fin:internalorderaccounting")]
    public partial class InternalOrderQueryByID
    {

        private string orderNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "token", Order = 0)]
        public string OrderNumber
        {
            get
            {
                return this.orderNumberField;
            }
            set
            {
                this.orderNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:kpmg:de:erp:sap:fin:internalorderaccounting")]
    public partial class UserStatusForOrder
    {

        private string statusProfileField;

        private string userStatusField;

        private string statusOrderNumberField;

        private string individualObjectStatusIDField;

        private string objectStatusDescriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string StatusProfile
        {
            get
            {
                return this.statusProfileField;
            }
            set
            {
                this.statusProfileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string UserStatus
        {
            get
            {
                return this.userStatusField;
            }
            set
            {
                this.userStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer", Order = 2)]
        public string StatusOrderNumber
        {
            get
            {
                return this.statusOrderNumberField;
            }
            set
            {
                this.statusOrderNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string IndividualObjectStatusID
        {
            get
            {
                return this.individualObjectStatusIDField;
            }
            set
            {
                this.individualObjectStatusIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string ObjectStatusDescription
        {
            get
            {
                return this.objectStatusDescriptionField;
            }
            set
            {
                this.objectStatusDescriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:kpmg:de:erp:sap:fin:internalorderaccounting")]
    public partial class SystemStatusForOrder
    {

        private string systemStatusField;

        private string individualObjectStatusField;

        private string objectStatusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string SystemStatus
        {
            get
            {
                return this.systemStatusField;
            }
            set
            {
                this.systemStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string IndividualObjectStatus
        {
            get
            {
                return this.individualObjectStatusField;
            }
            set
            {
                this.individualObjectStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string ObjectStatus
        {
            get
            {
                return this.objectStatusField;
            }
            set
            {
                this.objectStatusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:kpmg:de:erp:sap:fin:internalorderaccounting")]
    public partial class InternalOrder
    {

        private string orderNumberField;

        private string orderTypeField;

        private string descriptionField;

        private string externalOrderNumberField;

        private string objectNumberField;

        private string controllingAreaField;

        private string companyCodeField;

        private string businessAreaField;

        private string plantField;

        private string profitCenterField;

        private string responsibleCostCenterField;

        private string wBS_Element_IDField;

        private string wBS_Element_TextField;

        private string requestingCostCenterField;

        private string requestingCompanyCodeField;

        private string chargeableCodeField;

        private string itemNumberSalesOrderField;

        private string taxJurisdictionField;

        private string costCenterPostedToField;

        private string orderCurrencyField;

        private string costingSheetField;

        private string overheadKeyField;

        private string resultsAnalysisKeyField;

        private string interestProfileCalculationField;

        private string branchOfficeField;

        private string classificationField;

        private string engagementPartnerField;

        private string engagementManagerField;

        private string estimatedOrderTotalCostsField;

        private System.DateTime applicationDateField;

        private bool applicationDateFieldSpecified;

        private string departmentField;

        private System.DateTime workStartField;

        private bool workStartFieldSpecified;

        private System.DateTime endOfWorkField;

        private bool endOfWorkFieldSpecified;

        private string identifierEquivalenceOrderField;

        private string processingGroupField;

        private System.DateTime plannedReleaseDateField;

        private bool plannedReleaseDateFieldSpecified;

        private System.DateTime plannedCompletionDateField;

        private bool plannedCompletionDateFieldSpecified;

        private System.DateTime plannedClosingDateField;

        private bool plannedClosingDateFieldSpecified;

        private string requestingOrderField;

        private string functionalAreaShortTextField;

        private string functionalAreaLongTextField;

        private string userResponsibleOfInternalOrderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string OrderNumber
        {
            get
            {
                return this.orderNumberField;
            }
            set
            {
                this.orderNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string OrderType
        {
            get
            {
                return this.orderTypeField;
            }
            set
            {
                this.orderTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string ExternalOrderNumber
        {
            get
            {
                return this.externalOrderNumberField;
            }
            set
            {
                this.externalOrderNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string ObjectNumber
        {
            get
            {
                return this.objectNumberField;
            }
            set
            {
                this.objectNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string ControllingArea
        {
            get
            {
                return this.controllingAreaField;
            }
            set
            {
                this.controllingAreaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string CompanyCode
        {
            get
            {
                return this.companyCodeField;
            }
            set
            {
                this.companyCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string BusinessArea
        {
            get
            {
                return this.businessAreaField;
            }
            set
            {
                this.businessAreaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string Plant
        {
            get
            {
                return this.plantField;
            }
            set
            {
                this.plantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string ProfitCenter
        {
            get
            {
                return this.profitCenterField;
            }
            set
            {
                this.profitCenterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string ResponsibleCostCenter
        {
            get
            {
                return this.responsibleCostCenterField;
            }
            set
            {
                this.responsibleCostCenterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer", Order = 11)]
        public string WBS_Element_ID
        {
            get
            {
                return this.wBS_Element_IDField;
            }
            set
            {
                this.wBS_Element_IDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string WBS_Element_Text
        {
            get
            {
                return this.wBS_Element_TextField;
            }
            set
            {
                this.wBS_Element_TextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public string RequestingCostCenter
        {
            get
            {
                return this.requestingCostCenterField;
            }
            set
            {
                this.requestingCostCenterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public string RequestingCompanyCode
        {
            get
            {
                return this.requestingCompanyCodeField;
            }
            set
            {
                this.requestingCompanyCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public string ChargeableCode
        {
            get
            {
                return this.chargeableCodeField;
            }
            set
            {
                this.chargeableCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer", Order = 16)]
        public string ItemNumberSalesOrder
        {
            get
            {
                return this.itemNumberSalesOrderField;
            }
            set
            {
                this.itemNumberSalesOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 17)]
        public string TaxJurisdiction
        {
            get
            {
                return this.taxJurisdictionField;
            }
            set
            {
                this.taxJurisdictionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 18)]
        public string CostCenterPostedTo
        {
            get
            {
                return this.costCenterPostedToField;
            }
            set
            {
                this.costCenterPostedToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "token", Order = 19)]
        public string OrderCurrency
        {
            get
            {
                return this.orderCurrencyField;
            }
            set
            {
                this.orderCurrencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 20)]
        public string CostingSheet
        {
            get
            {
                return this.costingSheetField;
            }
            set
            {
                this.costingSheetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 21)]
        public string OverheadKey
        {
            get
            {
                return this.overheadKeyField;
            }
            set
            {
                this.overheadKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 22)]
        public string ResultsAnalysisKey
        {
            get
            {
                return this.resultsAnalysisKeyField;
            }
            set
            {
                this.resultsAnalysisKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 23)]
        public string InterestProfileCalculation
        {
            get
            {
                return this.interestProfileCalculationField;
            }
            set
            {
                this.interestProfileCalculationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 24)]
        public string BranchOffice
        {
            get
            {
                return this.branchOfficeField;
            }
            set
            {
                this.branchOfficeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 25)]
        public string Classification
        {
            get
            {
                return this.classificationField;
            }
            set
            {
                this.classificationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 26)]
        public string EngagementPartner
        {
            get
            {
                return this.engagementPartnerField;
            }
            set
            {
                this.engagementPartnerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 27)]
        public string EngagementManager
        {
            get
            {
                return this.engagementManagerField;
            }
            set
            {
                this.engagementManagerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 28)]
        public string EstimatedOrderTotalCosts
        {
            get
            {
                return this.estimatedOrderTotalCostsField;
            }
            set
            {
                this.estimatedOrderTotalCostsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 29)]
        public System.DateTime ApplicationDate
        {
            get
            {
                return this.applicationDateField;
            }
            set
            {
                this.applicationDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApplicationDateSpecified
        {
            get
            {
                return this.applicationDateFieldSpecified;
            }
            set
            {
                this.applicationDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 30)]
        public string Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 31)]
        public System.DateTime WorkStart
        {
            get
            {
                return this.workStartField;
            }
            set
            {
                this.workStartField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WorkStartSpecified
        {
            get
            {
                return this.workStartFieldSpecified;
            }
            set
            {
                this.workStartFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 32)]
        public System.DateTime EndOfWork
        {
            get
            {
                return this.endOfWorkField;
            }
            set
            {
                this.endOfWorkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndOfWorkSpecified
        {
            get
            {
                return this.endOfWorkFieldSpecified;
            }
            set
            {
                this.endOfWorkFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 33)]
        public string IdentifierEquivalenceOrder
        {
            get
            {
                return this.identifierEquivalenceOrderField;
            }
            set
            {
                this.identifierEquivalenceOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer", Order = 34)]
        public string ProcessingGroup
        {
            get
            {
                return this.processingGroupField;
            }
            set
            {
                this.processingGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 35)]
        public System.DateTime PlannedReleaseDate
        {
            get
            {
                return this.plannedReleaseDateField;
            }
            set
            {
                this.plannedReleaseDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlannedReleaseDateSpecified
        {
            get
            {
                return this.plannedReleaseDateFieldSpecified;
            }
            set
            {
                this.plannedReleaseDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 36)]
        public System.DateTime PlannedCompletionDate
        {
            get
            {
                return this.plannedCompletionDateField;
            }
            set
            {
                this.plannedCompletionDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlannedCompletionDateSpecified
        {
            get
            {
                return this.plannedCompletionDateFieldSpecified;
            }
            set
            {
                this.plannedCompletionDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 37)]
        public System.DateTime PlannedClosingDate
        {
            get
            {
                return this.plannedClosingDateField;
            }
            set
            {
                this.plannedClosingDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlannedClosingDateSpecified
        {
            get
            {
                return this.plannedClosingDateFieldSpecified;
            }
            set
            {
                this.plannedClosingDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 38)]
        public string RequestingOrder
        {
            get
            {
                return this.requestingOrderField;
            }
            set
            {
                this.requestingOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 39)]
        public string FunctionalAreaShortText
        {
            get
            {
                return this.functionalAreaShortTextField;
            }
            set
            {
                this.functionalAreaShortTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 40)]
        public string FunctionalAreaLongText
        {
            get
            {
                return this.functionalAreaLongTextField;
            }
            set
            {
                this.functionalAreaLongTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 41)]
        public string UserResponsibleOfInternalOrder
        {
            get
            {
                return this.userResponsibleOfInternalOrderField;
            }
            set
            {
                this.userResponsibleOfInternalOrderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:kpmg:de:erp:sap:fin:internalorderaccounting")]
    public partial class ProcessingReturn
    {

        private string processingReturnCodeField;

        private string processingMessageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "token", Order = 0)]
        public string ProcessingReturnCode
        {
            get
            {
                return this.processingReturnCodeField;
            }
            set
            {
                this.processingReturnCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string ProcessingMessage
        {
            get
            {
                return this.processingMessageField;
            }
            set
            {
                this.processingMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:kpmg:de:erp:sap:fin:internalorderaccounting")]
    public partial class InternalOrderResponseDetails
    {

        private InternalOrderResponseDetailsMessageHeader messageHeaderField;

        private InternalOrder internalOrderField;

        private SystemStatusForOrder[] systemStatusForOrderField;

        private UserStatusForOrder[] userStatusForOrderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public InternalOrderResponseDetailsMessageHeader MessageHeader
        {
            get
            {
                return this.messageHeaderField;
            }
            set
            {
                this.messageHeaderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public InternalOrder InternalOrder
        {
            get
            {
                return this.internalOrderField;
            }
            set
            {
                this.internalOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SystemStatusForOrder", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public SystemStatusForOrder[] SystemStatusForOrder
        {
            get
            {
                return this.systemStatusForOrderField;
            }
            set
            {
                this.systemStatusForOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UserStatusForOrder", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public UserStatusForOrder[] UserStatusForOrder
        {
            get
            {
                return this.userStatusForOrderField;
            }
            set
            {
                this.userStatusForOrderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:kpmg:de:erp:sap:fin:internalorderaccounting")]
    public partial class InternalOrderResponseDetailsMessageHeader
    {

        private ProcessingReturn processingReturnField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ProcessingReturn ProcessingReturn
        {
            get
            {
                return this.processingReturnField;
            }
            set
            {
                this.processingReturnField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class NonChargeableCodeByIDReadQueryRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:kpmg:de:erp:nonsap:fin:nonchargeablecode", Order = 0)]
        public InternalOrderQueryByID NonChargeableCodeReadQuery;

        public NonChargeableCodeByIDReadQueryRequest()
        {
        }

        public NonChargeableCodeByIDReadQueryRequest(InternalOrderQueryByID NonChargeableCodeReadQuery)
        {
            this.NonChargeableCodeReadQuery = NonChargeableCodeReadQuery;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class NonChargeableCodeByIDReadQueryResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:kpmg:de:erp:nonsap:fin:nonchargeablecode", Order = 0)]
        public InternalOrderResponseDetails NonChargeableCodeReadResponse;

        public NonChargeableCodeByIDReadQueryResponse()
        {
        }

        public NonChargeableCodeByIDReadQueryResponse(InternalOrderResponseDetails NonChargeableCodeReadResponse)
        {
            this.NonChargeableCodeReadResponse = NonChargeableCodeReadResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NonChargeableCodeByIDQuery_OutbChannel : NonChargeableCodeByIDQuery_Outb, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NonChargeableCodeByIDQuery_OutbClient : System.ServiceModel.ClientBase<NonChargeableCodeByIDQuery_Outb>, NonChargeableCodeByIDQuery_Outb
    {

        public NonChargeableCodeByIDQuery_OutbClient()
        {
        }

        public NonChargeableCodeByIDQuery_OutbClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public NonChargeableCodeByIDQuery_OutbClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public NonChargeableCodeByIDQuery_OutbClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public NonChargeableCodeByIDQuery_OutbClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NonChargeableCodeByIDReadQueryResponse NonChargeableCodeByIDQuery_Outb.NonChargeableCodeByIDReadQuery(NonChargeableCodeByIDReadQueryRequest request)
        {
            return base.Channel.NonChargeableCodeByIDReadQuery(request);
        }

        public InternalOrderResponseDetails NonChargeableCodeByIDReadQuery(InternalOrderQueryByID NonChargeableCodeReadQuery)
        {
            NonChargeableCodeByIDReadQueryRequest inValue = new NonChargeableCodeByIDReadQueryRequest();
            inValue.NonChargeableCodeReadQuery = NonChargeableCodeReadQuery;
            NonChargeableCodeByIDReadQueryResponse retVal = ((NonChargeableCodeByIDQuery_Outb)(this)).NonChargeableCodeByIDReadQuery(inValue);
            return retVal.NonChargeableCodeReadResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NonChargeableCodeByIDReadQueryResponse> NonChargeableCodeByIDQuery_Outb.NonChargeableCodeByIDReadQueryAsync(NonChargeableCodeByIDReadQueryRequest request)
        {
            return base.Channel.NonChargeableCodeByIDReadQueryAsync(request);
        }

        public System.Threading.Tasks.Task<NonChargeableCodeByIDReadQueryResponse> NonChargeableCodeByIDReadQueryAsync(InternalOrderQueryByID NonChargeableCodeReadQuery)
        {
            NonChargeableCodeByIDReadQueryRequest inValue = new NonChargeableCodeByIDReadQueryRequest();
            inValue.NonChargeableCodeReadQuery = NonChargeableCodeReadQuery;
            return ((NonChargeableCodeByIDQuery_Outb)(this)).NonChargeableCodeByIDReadQueryAsync(inValue);
        }
    }
    namespace GeneratedNamespace1
    {


        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
        [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
        public partial class StandardMessageFault : object, System.Xml.Serialization.IXmlSerializable
        {

            private System.Xml.XmlNode[] nodesField;

            private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("StandardMessageFault", "");

            public System.Xml.XmlNode[] Nodes
            {
                get
                {
                    return this.nodesField;
                }
                set
                {
                    this.nodesField = value;
                }
            }

            public void ReadXml(System.Xml.XmlReader reader)
            {
                this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
            }

            public void WriteXml(System.Xml.XmlWriter writer)
            {
                System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
            }

            public System.Xml.Schema.XmlSchema GetSchema()
            {
                return null;
            }

            public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
            {
                System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
                return typeName;
            }
        }
    }

}
